import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@/styles/globals.css';
import '@/styles/custom.css';
import { ConfigProvider } from 'antd';
import Layout from '@/Layouts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const MontserratFont = Montserrat({
  subsets: ['vietnamese'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-montserrat',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${MontserratFont.variable} font-montserrat`}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: '#F26C4F',
            },
          }}
        >
          <Layout>
            {children}
            {/* <GoogleAnalytics gaId='G-5JCE19WNL6' /> */}
          </Layout>
        </ConfigProvider>
      </body>
    </html>
  );
}
